server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: server_back
  datasource:
    url: jdbc:postgresql://localhost:5433/devdb
    username: ups
    password: ups123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect